In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os 

#os.system('clear')

print(torch.__version__)

1.12.1+cu116


In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([7, 7])
MATRIX = torch.tensor([[7,8], [9,10]])
TENSOR = torch.tensor([[[1,2,0],[2,3,0],[3,4,0]]])

print(f'{scalar = }, {scalar.ndim = }, {scalar.item() = }\n')
print(f'{vector = }, {vector.ndim = }, {vector.shape = }\n')
print(f'{MATRIX = }, {MATRIX.ndim = }, {MATRIX.shape = }\n')
print(f'{TENSOR = }, {TENSOR.ndim = }, {TENSOR.shape = }\n')

scalar = tensor(7), scalar.ndim = 0, scalar.item() = 7

vector = tensor([7, 7]), vector.ndim = 1, vector.shape = torch.Size([2])

MATRIX = tensor([[ 7,  8],
        [ 9, 10]]), MATRIX.ndim = 2, MATRIX.shape = torch.Size([2, 2])

TENSOR = tensor([[[1, 2, 0],
         [2, 3, 0],
         [3, 4, 0]]]), TENSOR.ndim = 3, TENSOR.shape = torch.Size([1, 3, 3])



In [3]:
random_tensor = torch.rand(size=(3, 4, 2))
print(random_tensor.ndim)

random_img_tensor = torch.rand(size=(3, 224, 224)) #rgb, h, w
print(random_img_tensor.shape, random_img_tensor.ndim)

zeros_tensor = torch.zeros(size=(3, 4))
ones_tensor = torch.ones(size=(3, 4))

print(zeros_tensor, '\n', ones_tensor)

range_tensor = torch.arange(0, 10, 2)
print(range_tensor)

like_tensor = torch.zeros_like(input=range_tensor)
print(like_tensor)
like_tensor

3
torch.Size([3, 224, 224]) 3
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0, 0, 0, 0, 0])


tensor([0, 0, 0, 0, 0])

In [4]:
# types

f32_tensor = torch.tensor(
    [3, 4, 5], 
    dtype=torch.float32,    # datatype
    device='cuda',          # 'cpu', 'gpu'
    requires_grad=False,    # track gradients
    )

f16_tensor = torch.tensor(
    [3, 4, 5], 
    dtype=torch.float16,    # datatype
    device='cuda',          # 'cpu', 'gpu'
    requires_grad=False,    # track gradients
    )
i32_tensor = torch.tensor(
    [3, 4, 5], 
    dtype=torch.int32,    # datatype
    device='cuda',          # 'cpu', 'gpu'
    requires_grad=False,    # track gradients
    )

print(torch.float16 == torch.half)
print(f32_tensor.device)

print((f32_tensor * f16_tensor).dtype)
print(f32_tensor * i32_tensor)

True
cuda:0
torch.float32
tensor([ 9., 16., 25.], device='cuda:0')


In [5]:
# operations

tensor = torch.tensor([1, 2, 3])

torch.add(tensor, 10)

# ou 

((tensor+10) * 10) - 10

tensor([100, 110, 120])

In [6]:
%%time

# element wise mul

tensorm1 = torch.tensor([1, 2, 3], dtype=torch.long)
print(tensorm1**2)

# matrix multiplication

print(torch.matmul(tensorm1, tensorm1))

tensor([1, 4, 9])
tensor(14)
CPU times: user 2.63 ms, sys: 0 ns, total: 2.63 ms
Wall time: 6.93 ms


In [7]:
# max, min, arg, mean, sum

tensor = torch.rand(1,5)

[ 
    tensor,
    tensor.argmin(),
    tensor.argmax(),
    tensor.min(),
    tensor.max(),
    tensor.sum(),
    torch.mean(tensor.type(torch.float32)),
    tensor.type(torch.float32).mean(),
]

[tensor([[0.4325, 0.7265, 0.4505, 0.5070, 0.8354]]),
 tensor(0),
 tensor(4),
 tensor(0.4325),
 tensor(0.8354),
 tensor(2.9518),
 tensor(0.5904),
 tensor(0.5904)]

In [8]:
# reshaping

tensor = torch.rand(1,5,2)

[
    tensor,
    tensor.flatten(),
    tensor.reshape(2,5)
]

[tensor([[[0.4251, 0.4970],
          [0.1012, 0.1463],
          [0.2669, 0.0608],
          [0.2349, 0.3046],
          [0.0886, 0.3290]]]),
 tensor([0.4251, 0.4970, 0.1012, 0.1463, 0.2669, 0.0608, 0.2349, 0.3046, 0.0886,
         0.3290]),
 tensor([[0.4251, 0.4970, 0.1012, 0.1463, 0.2669],
         [0.0608, 0.2349, 0.3046, 0.0886, 0.3290]])]

In [9]:
tensor = torch.arange(1, 7)

tensorview = tensor.view(1, 6) # same memory address

tensorview[:, 0] = -1 

stack0 = torch.stack([tensor, tensor, tensor], dim=0)
stack1 = torch.stack([tensor, tensor, tensor], dim=1)

[
    tensorview,
    tensor,
    tensor,
    stack0,
    stack1,
]

[tensor([[-1,  2,  3,  4,  5,  6]]),
 tensor([-1,  2,  3,  4,  5,  6]),
 tensor([-1,  2,  3,  4,  5,  6]),
 tensor([[-1,  2,  3,  4,  5,  6],
         [-1,  2,  3,  4,  5,  6],
         [-1,  2,  3,  4,  5,  6]]),
 tensor([[-1, -1, -1],
         [ 2,  2,  2],
         [ 3,  3,  3],
         [ 4,  4,  4],
         [ 5,  5,  5],
         [ 6,  6,  6]])]

In [10]:
# squeeze - remove single dimensions

tensor = torch.arange(1,9).reshape([1,4,2])
[
    tensor,
    tensor.shape,
    '',
    tensor.squeeze(),
    tensor.squeeze().shape,
    '',
    tensor.unsqueeze(dim=0).unsqueeze(dim=0),
    tensor.unsqueeze(dim=0).unsqueeze(dim=0).squeeze().shape
]

[tensor([[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]),
 torch.Size([1, 4, 2]),
 '',
 tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]),
 '',
 tensor([[[[[1, 2],
            [3, 4],
            [5, 6],
            [7, 8]]]]]),
 torch.Size([4, 2])]

In [11]:
random_img = torch.rand(size=(224, 224, 3))
idx120 = random_img[1, 2, 0]

# permute original tensor to rearrange the axis

# obs: permute is a view() of the original tensor
# 0->1, 1->2, 2->0
img_permuted = random_img.permute(2, 0, 1)
idx012 = img_permuted[0, 1, 2]

[
    random_img.shape,
    idx120,
    img_permuted.shape,
    idx012,
]


[torch.Size([224, 224, 3]),
 tensor(0.3054),
 torch.Size([3, 224, 224]),
 tensor(0.3054)]

In [20]:
tensor = torch.arange(1,10).reshape([1,3,3])

[
    tensor,
    tensor[0, 0],
    tensor[:, :, 1]
]

[tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([1, 2, 3]),
 tensor([[2, 5, 8]])]

In [26]:
import torch
import numpy as np

# from_numpy x numpy() don't share the memory address 

# dtype padrão = f32 
array_np = np.arange(1, 8.0)

# type padrão = f64
tensor = torch.from_numpy(array_np).type(torch.float32)

tensor_np = tensor.numpy()

array_np, tensor, tensor_np

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [52]:
# same memory address

RANDOM_SEED = 999
torch.manual_seed(RANDOM_SEED)

tensor1 = torch.rand([7])
tensor2 = tensor1

tensor2[0] = -1

tensor1, tensor2, torch.rand([7])

(tensor([-1.0000,  0.6531,  0.0457,  0.9424,  0.4925,  0.9985,  0.7585]),
 tensor([-1.0000,  0.6531,  0.0457,  0.9424,  0.4925,  0.9985,  0.7585]),
 tensor([0.0317, 0.2769, 0.9590, 0.0498, 0.1786, 0.4095, 0.5523]))

In [81]:
import torch


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

tensor = torch.tensor([1, 2, 3])

# numpy doesn't work with device = 'cuda'

tensor.device, tensor.to('cuda'), tensor.to('cuda').to('cpu').cuda().cpu()


cuda


(device(type='cpu'), tensor([1, 2, 3], device='cuda:0'), tensor([1, 2, 3]))